
CREATE TABLE PAIS (
    id_pais NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 3),
    nom_pais VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PAIS PRIMARY KEY (id_pais)
);

CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3),
    nom_ciudad VARCHAR2(30) NOT NULL,
    cod_pais NUMBER(3) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (id_ciudad),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (cod_pais) REFERENCES PAIS(id_pais)
);

CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3),
    nom_sucursal VARCHAR2(20) NOT NULL,
    cod_ciudad NUMBER(3) NOT NULL,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (id_sucursal),
    CONSTRAINT FK_SUCURSAL_CIUDAD FOREIGN KEY (cod_ciudad) REFERENCES CIUDAD(id_ciudad)
);

CREATE TABLE MECANICO (
    cod_mecanico NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 460 INCREMENT BY 7),
    pnombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    apaterno VARCHAR2(20) NOT NULL,
    sueldo NUMBER(10) NOT NULL,
    monto_impuestos NUMBER(10),
    bono_jefatura NUMBER(10),
    cod_supervisor NUMBER(5),
    CONSTRAINT PK_MECANICO PRIMARY KEY (cod_mecanico),
    CONSTRAINT FK_MECANICO_SUP FOREIGN KEY (cod_supervisor) REFERENCES MECANICO(cod_mecanico),
    CONSTRAINT CK_MECANICO_SUELDO CHECK (sueldo >= 510000) -- Regla
);

CREATE TABLE CLIENTE (
    rut NUMBER(9),
    dv CHAR(1) NOT NULL,
    pnombre VARCHAR2(20) NOT NULL,
    apaterno VARCHAR2(20) NOT NULL,
    email VARCHAR2(40),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (rut),
    CONSTRAINT UN_CLIENTE_EMAIL UNIQUE (email), -- Regla
    CONSTRAINT CK_CLIENTE_DV CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K')) -- Regla
);

-- Tabla MANTENCION con PK Compuesta (Caso 2)
CREATE TABLE MANTENCION (
    num_mantencion NUMBER(6),
    cod_sucursal CHAR(3),
    fecha_ingreso DATE NOT NULL,
    patente_auto CHAR(8) NOT NULL,
    cod_mecanico NUMBER(5) NOT NULL,
    estado VARCHAR2(15),
    CONSTRAINT PK_MANTENCION_SUC PRIMARY KEY (num_mantencion, cod_sucursal), -- Regla Caso 2
    CONSTRAINT FK_MANT_SUCURSAL FOREIGN KEY (cod_sucursal) REFERENCES SUCURSAL(id_sucursal),
    CONSTRAINT CK_MANT_ESTADO CHECK (estado IN ('Reserva', 'Ingresado', 'Entregado', 'Anulado')) -- Regla
);

-- 1. Crear Secuencias
CREATE SEQUENCE SEQ_SERVICIO START WITH 400 INCREMENT BY 2; -- Requisito
CREATE SEQUENCE SEQ_CIUDAD START WITH 165 INCREMENT BY 5;   -- Requisito

-- 2. Poblamiento

INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais) 
VALUES (SEQ_CIUDAD.NEXTVAL, 'Santiago', 9);
INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais) 
VALUES (SEQ_CIUDAD.NEXTVAL, 'Valparaíso', 9);

INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad) 
VALUES ('S01', 'Sucursal Norte', 'Av. Libertad', 1200, 165);

INSERT INTO MECANICO (pnombre, apaterno, sueldo, cod_supervisor) 
VALUES ('Juan', 'Pérez', 550000, NULL);
INSERT INTO MECANICO (pnombre, apaterno, sueldo, cod_supervisor) 
VALUES ('Andrés', 'Gómez', 600000, 460);

INSERT INTO SERVICIO (id_servicio, descripcion, costo) 
VALUES (SEQ_SERVICIO.NEXTVAL, 'Cambio de Aceite', 45000);
INSERT INTO SERVICIO (id_servicio, descripcion, costo) 
VALUES (SEQ_SERVICIO.NEXTVAL, 'Alineación y Balanceo', 35000);

INSERT INTO CLIENTE (rut, dv, pnombre, apaterno, tipo_cli, email) 
VALUES (12345678, '5', 'Carlos', 'Ruiz', 'P', 'cruiz@email.com');

INSERT INTO AUTOMOVIL (patente, annio, cod_tipo_auto, cod_modelo, cl_rut) 
VALUES ('ABCD-12', 2022, 'SED', 10, 12345678);

INSERT INTO MANTENCION (num_mantencion, cod_sucursal, fecha_ingreso, patente_auto, cod_mecanico, estado) 
VALUES (1001, 'S01', TO_DATE('2023-10-25', 'YYYY-MM-DD'), 'ABCD-12', 460, 'Ingresado');

INSERT INTO DETALLE_SERVICIO (mantencion_num, cod_sucursal, cod_servicio, cantidad) 
VALUES (1001, 'S01', 400, 1);

--Informe 1
SELECT 
    cod_mecanico AS "ID MECANICO",
    pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
    sueldo AS "SALARIO",
    monto_impuestos AS "IMPUESTO ACTUAL",
    (monto_impuestos * 0.80) AS "IMPUESTO REBAJADO",
    sueldo - (monto_impuestos * 0.80) AS "SUELDO CON REBAJA IMPUESTOS"
FROM MECANICO
WHERE bono_jefatura IS NULL 
  AND monto_impuestos < 40000
ORDER BY "IMPUESTO ACTUAL" DESC, apaterno ASC;

--Informe 2
SELECT 
    cod_mecanico AS "IDENTIFICADOR",
    pnombre || ' ' || snombre || ' ' || apaterno AS "MECANICO",
    sueldo AS "SALARIO ACTUAL",
    (sueldo * 0.05) AS "AJUSTE",
    (sueldo * 1.05) AS "SUELDO_REAJUSTADO"
FROM MECANICO
WHERE (sueldo BETWEEN 600000 AND 900000) 
   OR cod_supervisor IS NULL
ORDER BY "SALARIO ACTUAL" ASC, "MECANICO" DESC;